#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libgusb
Version  : 0.2.11
Release  : 5
URL      : https://github.com/hughsie/libgusb/archive/gusb_0_2_11.tar.gz
Source0  : https://github.com/hughsie/libgusb/archive/gusb_0_2_11.tar.gz
Summary  : GUsb is a GLib binding for libusb1
Group    : Development/Tools
License  : LGPL-2.1
Requires: libgusb-bin
Requires: libgusb-data
Requires: libgusb-lib
BuildRequires : docbook-xml
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(libusb-1.0)
BuildRequires : vala-dev

%description
GUsb is a GObject wrapper for libusb1 that makes it easy to do
asynchronous control, bulk and interrupt transfers with proper
cancellation and integration into a mainloop.
This makes it easy to integrate low level USB transfers with your
high-level application or system daemon.

%package bin
Summary: bin components for the libgusb package.
Group: Binaries
Requires: libgusb-data

%description bin
bin components for the libgusb package.


%package data
Summary: data components for the libgusb package.
Group: Data

%description data
data components for the libgusb package.


%package dev
Summary: dev components for the libgusb package.
Group: Development
Requires: libgusb-lib
Requires: libgusb-bin
Requires: libgusb-data
Provides: libgusb-devel

%description dev
dev components for the libgusb package.


%package lib
Summary: lib components for the libgusb package.
Group: Libraries
Requires: libgusb-data

%description lib
lib components for the libgusb package.


%prep
%setup -q -n libgusb-gusb_0_2_11

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1523661662
%autogen --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1523661662
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gusbcmd

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/GUsb-1.0.typelib
/usr/share/gir-1.0/*.gir
/usr/share/vala/vapi/gusb.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/gusb-1/gusb-private.h
/usr/include/gusb-1/gusb.h
/usr/include/gusb-1/gusb/gusb-autocleanups.h
/usr/include/gusb-1/gusb/gusb-context-private.h
/usr/include/gusb-1/gusb/gusb-context.h
/usr/include/gusb-1/gusb/gusb-device-list.h
/usr/include/gusb-1/gusb/gusb-device-private.h
/usr/include/gusb-1/gusb/gusb-device.h
/usr/include/gusb-1/gusb/gusb-interface-private.h
/usr/include/gusb-1/gusb/gusb-interface.h
/usr/include/gusb-1/gusb/gusb-source.h
/usr/include/gusb-1/gusb/gusb-util.h
/usr/include/gusb-1/gusb/gusb-version.h
/usr/lib64/libgusb.so
/usr/lib64/pkgconfig/gusb.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgusb.so.2
/usr/lib64/libgusb.so.2.0.10
