#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libgusb
Version  : 0.4.0
Release  : 15
URL      : https://github.com/hughsie/libgusb/archive/0.4.0/libgusb-0.4.0.tar.gz
Source0  : https://github.com/hughsie/libgusb/archive/0.4.0/libgusb-0.4.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: libgusb-bin = %{version}-%{release}
Requires: libgusb-data = %{version}-%{release}
Requires: libgusb-lib = %{version}-%{release}
Requires: libgusb-license = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : clr-hardware-files
BuildRequires : gobject-introspection-dev
BuildRequires : json-glib-dev
BuildRequires : libusb-dev
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : pkgconfig(libusb-1.0)
BuildRequires : pkgconfig(umockdev-1.0)
BuildRequires : vala-dev

%description
GUsb
====
GUsb is a GObject wrapper for libusb1 that makes it easy to do
asynchronous control, bulk and interrupt transfers with proper
cancellation and integration into a mainloop.
This makes it easy to integrate low level USB transfers with your
high-level application or system daemon.

%package bin
Summary: bin components for the libgusb package.
Group: Binaries
Requires: libgusb-data = %{version}-%{release}
Requires: libgusb-license = %{version}-%{release}

%description bin
bin components for the libgusb package.


%package data
Summary: data components for the libgusb package.
Group: Data

%description data
data components for the libgusb package.


%package dev
Summary: dev components for the libgusb package.
Group: Development
Requires: libgusb-lib = %{version}-%{release}
Requires: libgusb-bin = %{version}-%{release}
Requires: libgusb-data = %{version}-%{release}
Provides: libgusb-devel = %{version}-%{release}
Requires: libgusb = %{version}-%{release}

%description dev
dev components for the libgusb package.


%package lib
Summary: lib components for the libgusb package.
Group: Libraries
Requires: libgusb-data = %{version}-%{release}
Requires: libgusb-license = %{version}-%{release}

%description lib
lib components for the libgusb package.


%package license
Summary: license components for the libgusb package.
Group: Default

%description license
license components for the libgusb package.


%prep
%setup -q -n libgusb-0.4.0
cd %{_builddir}/libgusb-0.4.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1663001007
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Ddocs=false  builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs

%install
mkdir -p %{buildroot}/usr/share/package-licenses/libgusb
cp %{_builddir}/libgusb-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libgusb/9a1929f4700d2407c70b507b3b2aaf6226a9543c
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gusbcmd

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/GUsb-1.0.typelib
/usr/share/gir-1.0/*.gir
/usr/share/vala/vapi/gusb.deps
/usr/share/vala/vapi/gusb.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/gusb-1/gusb.h
/usr/include/gusb-1/gusb/gusb-bos-descriptor-private.h
/usr/include/gusb-1/gusb/gusb-bos-descriptor.h
/usr/include/gusb-1/gusb/gusb-context-private.h
/usr/include/gusb-1/gusb/gusb-context.h
/usr/include/gusb-1/gusb/gusb-device-event.h
/usr/include/gusb-1/gusb/gusb-device-list.h
/usr/include/gusb-1/gusb/gusb-device-private.h
/usr/include/gusb-1/gusb/gusb-device.h
/usr/include/gusb-1/gusb/gusb-endpoint-private.h
/usr/include/gusb-1/gusb/gusb-endpoint.h
/usr/include/gusb-1/gusb/gusb-interface-private.h
/usr/include/gusb-1/gusb/gusb-interface.h
/usr/include/gusb-1/gusb/gusb-source.h
/usr/include/gusb-1/gusb/gusb-util.h
/usr/include/gusb-1/gusb/gusb-version.h
/usr/lib64/libgusb.so
/usr/lib64/pkgconfig/gusb.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgusb.so.2
/usr/lib64/libgusb.so.2.0.10

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libgusb/9a1929f4700d2407c70b507b3b2aaf6226a9543c
